version: '3.8'

services:
  backend:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - ./backend/main.py:/app/main.py
    environment:
      - ENV=development

  frontend:
    image: node:alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - REACT_APP_API_BASE=http://localhost:8000